app:
  host: 0.0.0.0
  port: 18880
  logLevel: info
  apiToken: ""

supervisor:
  confDir: /etc/supervisord.d
  commandTimeoutSeconds: 30
  templateDefaults:
    startsecs: 10
    startretries: 3
    redirect_stderr: true
    stdout_logfile_maxbytes: 1GB
    stdout_logfile_backups: 1
    stopasgroup: false
    killasgroup: false

executor:
  type: local
  inventoryPath: /etc/ansible/deploy_host
  remoteUser: root
  timeoutSeconds: 30

hosts:
  - name: local
    ip: 127.0.0.1
    enabled: true
    executorType: local
  - name: web-99
    ip: 10.1.0.99
    enabled: true
    executorType: ansible
    ansiblePattern: web-99
  - name: web-104
    ip: 10.1.0.104
    enabled: true
    executorType: ansible
    ansiblePattern: web-104
  - name: web-252
    ip: 101.1.0.252
    enabled: true
    executorType: ansible
    ansiblePattern: web-252
