app:
  host: 0.0.0.0
  port: 18881
  logLevel: info

database:
  host: 106.54.205.33
  port: 3306
  name: be_supervisor_model
  user: root
  connectTimeoutSeconds: 5

auth:
  accessTokenExpireMinutes: 480

supervisor:
  confDir: /etc/supervisord.d
  commandTimeoutSeconds: 300

executor:
  type: local
  inventoryPath: /Users/zhuningkang/.ansible/supervisor_host
  remoteUser: root
  timeoutSeconds: 300

hosts:
#  - name: local
#    ip: 127.0.0.1
#    enabled: true
#    executorType: local
  - name: web-99
    ip: 10.1.0.99
    enabled: true
    executorType: ansible
  - name: web-104
    ip: 10.1.0.104
    enabled: true
    executorType: ansible
  - name: web-252
    ip: 101.1.0.252
    enabled: true
    executorType: ansible
