services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-supervisor-model
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      APP_ENV: prod
      APP_CONFIG_PATH: /app/config.yaml
      APP_LOG_PATH: /var/log/be-supervisor-model/app.log
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - /etc/ansible:/etc/ansible:ro
      - /data/logs/be-supervisor-model/:/var/log/be-supervisor-model
    ports:
      - "18881:18881"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
