CREATE TABLE IF NOT EXISTS `sys_user` (
    `id` BIGINT NOT NULL PRIMARY KEY COMMENT 'ID',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `user_name` VARCHAR(50) NOT NULL COMMENT '用户名',
    `nick_name` VARCHAR(50) DEFAULT NULL COMMENT '昵称',
    `password` VARCHAR(255) NOT NULL COMMENT '密码哈希',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0禁用',
    `is_super_admin` TINYINT NOT NULL DEFAULT 0 COMMENT '是否超级管理员 1是 0否',
    `login_time` DATETIME DEFAULT NULL COMMENT '最近登录时间',
    `login_address` VARCHAR(128) DEFAULT NULL COMMENT '最近登录地址',
    `pwd_update_date` DATETIME DEFAULT NULL COMMENT '密码最后更新时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除 0否 1是',
    `create_by_id` BIGINT DEFAULT NULL COMMENT '新增人ID',
    `create_by` VARCHAR(50) DEFAULT NULL COMMENT '新增人名称',
    `update_by_id` BIGINT DEFAULT NULL COMMENT '更新人ID',
    `update_by` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    `version` BIGINT DEFAULT 0 COMMENT '乐观锁版本',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    UNIQUE KEY `uk_user_name` (`user_name`),
    KEY `idx_user_user_name` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户信息表';

CREATE TABLE IF NOT EXISTS `sys_login_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `user_id` BIGINT DEFAULT NULL COMMENT '用户ID',
    `token_id` BIGINT DEFAULT NULL COMMENT '登录令牌ID',
    `user_name` VARCHAR(50) DEFAULT '' COMMENT '用户名',
    `ipaddr` VARCHAR(128) DEFAULT '' COMMENT '登录IP',
    `login_location` VARCHAR(255) DEFAULT '' COMMENT '登录地点',
    `browser` VARCHAR(50) DEFAULT '' COMMENT '浏览器',
    `os` VARCHAR(50) DEFAULT '' COMMENT '操作系统',
    `status` CHAR(1) DEFAULT '0' COMMENT '登录状态 0成功 1失败',
    `msg` VARCHAR(255) DEFAULT '' COMMENT '提示消息',
    `token_jti` VARCHAR(64) DEFAULT NULL COMMENT 'JWT令牌JTI',
    `login_time` DATETIME DEFAULT NULL COMMENT '登录时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除 0否 1是',
    `create_by_id` BIGINT DEFAULT NULL COMMENT '新增人ID',
    `create_by` VARCHAR(50) DEFAULT NULL COMMENT '新增人名称',
    `update_by_id` BIGINT DEFAULT NULL COMMENT '更新人ID',
    `update_by` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    `version` BIGINT DEFAULT 0 COMMENT '乐观锁版本',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    KEY `idx_login_log_status` (`status`),
    KEY `idx_login_log_time` (`login_time`),
    KEY `idx_login_log_user_id` (`user_id`),
    KEY `idx_login_log_token_id` (`token_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='登录审计日志表';

CREATE TABLE IF NOT EXISTS `sys_login_token` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `user_name` VARCHAR(50) NOT NULL COMMENT '用户名',
    `token_jti` VARCHAR(64) NOT NULL COMMENT 'JWT令牌JTI',
    `token_digest` CHAR(64) NOT NULL COMMENT 'JWT令牌摘要',
    `login_ip` VARCHAR(128) DEFAULT '' COMMENT '登录IP',
    `user_agent` VARCHAR(500) DEFAULT '' COMMENT '客户端标识',
    `issued_at` DATETIME NOT NULL COMMENT '签发时间',
    `expires_at` DATETIME NOT NULL COMMENT '过期时间',
    `revoked_time` DATETIME DEFAULT NULL COMMENT '注销时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除 0否 1是',
    `create_by_id` BIGINT DEFAULT NULL COMMENT '新增人ID',
    `create_by` VARCHAR(50) DEFAULT NULL COMMENT '新增人名称',
    `update_by_id` BIGINT DEFAULT NULL COMMENT '更新人ID',
    `update_by` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    `version` BIGINT DEFAULT 0 COMMENT '乐观锁版本',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    UNIQUE KEY `uk_login_token_jti` (`token_jti`),
    KEY `idx_login_token_user_id` (`user_id`),
    KEY `idx_login_token_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='JWT登录令牌表';
