CREATE TABLE IF NOT EXISTS `sys_user` (
    `id` BIGINT NOT NULL PRIMARY KEY,
    `tenant_id` BIGINT DEFAULT NULL,
    `user_name` VARCHAR(50) NOT NULL,
    `nick_name` VARCHAR(50) DEFAULT NULL,
    `password` VARCHAR(255) NOT NULL,
    `status` TINYINT NOT NULL DEFAULT 1,
    `is_super_admin` TINYINT NOT NULL DEFAULT 0,
    `login_time` DATETIME DEFAULT NULL,
    `login_address` VARCHAR(128) DEFAULT NULL,
    `pwd_update_date` DATETIME DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `is_deleted` TINYINT NOT NULL DEFAULT 0,
    `create_by_id` BIGINT DEFAULT NULL,
    `create_by` VARCHAR(50) DEFAULT NULL,
    `update_by_id` BIGINT DEFAULT NULL,
    `update_by` VARCHAR(50) DEFAULT NULL,
    `version` BIGINT DEFAULT 0,
    `remark` VARCHAR(500) DEFAULT NULL,
    UNIQUE KEY `uk_user_name` (`user_name`),
    KEY `idx_user_user_name` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户信息表';

CREATE TABLE IF NOT EXISTS `sys_login_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `tenant_id` BIGINT DEFAULT NULL,
    `user_id` BIGINT DEFAULT NULL,
    `session_id` BIGINT DEFAULT NULL,
    `user_name` VARCHAR(50) DEFAULT '',
    `ipaddr` VARCHAR(128) DEFAULT '',
    `login_location` VARCHAR(255) DEFAULT '',
    `browser` VARCHAR(50) DEFAULT '',
    `os` VARCHAR(50) DEFAULT '',
    `status` CHAR(1) DEFAULT '0',
    `msg` VARCHAR(255) DEFAULT '',
    `token_jti` VARCHAR(64) DEFAULT NULL,
    `login_time` DATETIME DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `is_deleted` TINYINT NOT NULL DEFAULT 0,
    `create_by_id` BIGINT DEFAULT NULL,
    `create_by` VARCHAR(50) DEFAULT NULL,
    `update_by_id` BIGINT DEFAULT NULL,
    `update_by` VARCHAR(50) DEFAULT NULL,
    `version` BIGINT DEFAULT 0,
    `remark` VARCHAR(500) DEFAULT NULL,
    KEY `idx_login_log_status` (`status`),
    KEY `idx_login_log_time` (`login_time`),
    KEY `idx_login_log_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='登录审计日志表';

CREATE TABLE IF NOT EXISTS `sys_login_session` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `tenant_id` BIGINT DEFAULT NULL,
    `user_id` BIGINT NOT NULL,
    `user_name` VARCHAR(50) NOT NULL,
    `token_jti` VARCHAR(64) NOT NULL,
    `token_digest` CHAR(64) NOT NULL,
    `login_ip` VARCHAR(128) DEFAULT '',
    `user_agent` VARCHAR(500) DEFAULT '',
    `issued_at` DATETIME NOT NULL,
    `expires_at` DATETIME NOT NULL,
    `revoked_time` DATETIME DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `is_deleted` TINYINT NOT NULL DEFAULT 0,
    `create_by_id` BIGINT DEFAULT NULL,
    `create_by` VARCHAR(50) DEFAULT NULL,
    `update_by_id` BIGINT DEFAULT NULL,
    `update_by` VARCHAR(50) DEFAULT NULL,
    `version` BIGINT DEFAULT 0,
    `remark` VARCHAR(500) DEFAULT NULL,
    UNIQUE KEY `uk_login_session_jti` (`token_jti`),
    KEY `idx_login_session_user_id` (`user_id`),
    KEY `idx_login_session_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='JWT登录会话表';
