CREATE TABLE IF NOT EXISTS `sys_supervisor_service` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    `host_ip` VARCHAR(64) NOT NULL COMMENT '目标主机IP',
    `job_name` VARCHAR(128) NOT NULL COMMENT '业务作业名称',
    `module_name` VARCHAR(128) NOT NULL COMMENT '模块名称',
    `program_name` VARCHAR(255) NOT NULL COMMENT 'Supervisor服务名',
    `config_name` VARCHAR(255) NOT NULL COMMENT '配置文件名',
    `java_path` VARCHAR(500) NOT NULL COMMENT 'Java可执行文件绝对路径',
    `active_profile` VARCHAR(64) NOT NULL COMMENT 'Spring profile环境',
    `port` INT NOT NULL COMMENT '服务监听端口',
    `jar_name` VARCHAR(255) NOT NULL COMMENT 'Jar包文件名',
    `xms` VARCHAR(32) NOT NULL COMMENT 'JVM Xms 参数',
    `xmx` VARCHAR(32) NOT NULL COMMENT 'JVM Xmx 参数',
    `run_user` VARCHAR(64) NOT NULL COMMENT 'Supervisor运行用户',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by_id` BIGINT DEFAULT NULL COMMENT '新增人ID',
    `create_by` VARCHAR(50) DEFAULT NULL COMMENT '新增人名称',
    `update_by_id` BIGINT DEFAULT NULL COMMENT '更新人ID',
    `update_by` VARCHAR(50) DEFAULT NULL COMMENT '更新人名称',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    UNIQUE KEY `uk_supervisor_host_program` (`host_ip`, `program_name`),
    UNIQUE KEY `uk_supervisor_host_config` (`host_ip`, `config_name`),
    UNIQUE KEY `uk_supervisor_host_port` (`host_ip`, `port`),
    KEY `idx_supervisor_host` (`host_ip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
COMMENT='Supervisor服务主数据表';
